---
apiVersion: v1
kind: ConfigMap
metadata:
  name: covid-canada-node-app-config
data:
  COVID_CANADA_API: "https://api.covid19tracker.ca"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-canada-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-canada-node-app
  template:
    metadata:
      labels:
        app: covid-canada-node-app
    spec:
      containers:
      - name: covid-canada-node-app
        image: jasondippel/covid-canada-node-app:latest
        envFrom:
          - configMapRef:
              name: covid-canada-node-app-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 3001
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: covid-canada-service
spec:
  selector:
    app: covid-canada-node-app
  ports:
  - port: 3001
    targetPort: 3001
