---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-gateway-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-gateway-node-app
  template:
    metadata:
      labels:
        app: covid-gateway-node-app
    spec:
      containers:
      - name: covid-gateway-node-app
        image: jasondippel/covid-gateway-node-app:latest
        env:
          - name: COVID_API
            value: "http://covid-canada-service:3001"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: covid-gateway-service
spec:
  type: NodePort
  selector:
    app: covid-gateway-node-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
