---
apiVersion: v1
kind: ConfigMap
metadata:
  name: covid-gateway-node-app-config
data:
  COVID_API: "http://covid-canada-service:3001"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-gateway-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-gateway-node-app
  template:
    metadata:
      labels:
        app: covid-gateway-node-app
    spec:
      containers:
      - name: covid-gateway-node-app
        image: jasondippel/covid-gateway-node-app:latest
        envFrom:
          - configMapRef:
              name: covid-gateway-node-app-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: covid-gateway-service
spec:
  type: NodePort
  selector:
    app: covid-gateway-node-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
